
package SayiTabanUygulamasi;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class sayiTabanUygulamasi extends javax.swing.JFrame {
  
    JTextField field = new JTextField();
    
    
    /**
     * Creates new form sayiTabanUygulamasi
     */
    public sayiTabanUygulamasi() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ikiliktaban1 = new javax.swing.JRadioButton();
        sekizliktaban1 = new javax.swing.JRadioButton();
        onluktaban1 = new javax.swing.JRadioButton();
        onaltiliktaban1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ikiliktaban2 = new javax.swing.JRadioButton();
        sekizliktaban2 = new javax.swing.JRadioButton();
        onluktaban2 = new javax.swing.JRadioButton();
        onaltiliktaban2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        cevirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sayı Taban Uygulaması");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Çevrilecek sayı tabanını seçiniz:");

        buttonGroup1.add(ikiliktaban1);
        ikiliktaban1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ikiliktaban1.setText("İkilik taban");

        buttonGroup1.add(sekizliktaban1);
        sekizliktaban1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sekizliktaban1.setText("Sekizlik taban");

        buttonGroup1.add(onluktaban1);
        onluktaban1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        onluktaban1.setText("Onluk taban");

        buttonGroup1.add(onaltiliktaban1);
        onaltiliktaban1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        onaltiliktaban1.setText("Onaltılık taban");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ikiliktaban1)
                        .addGap(26, 26, 26)
                        .addComponent(sekizliktaban1)
                        .addGap(18, 18, 18)
                        .addComponent(onluktaban1)
                        .addGap(18, 18, 18)
                        .addComponent(onaltiliktaban1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikiliktaban1)
                    .addComponent(sekizliktaban1)
                    .addComponent(onluktaban1)
                    .addComponent(onaltiliktaban1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Sonuç hangi tabanda olacak :");

        buttonGroup2.add(ikiliktaban2);
        ikiliktaban2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ikiliktaban2.setText("İkilik taban");

        buttonGroup2.add(sekizliktaban2);
        sekizliktaban2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sekizliktaban2.setText("Sekizlik Taban");

        buttonGroup2.add(onluktaban2);
        onluktaban2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        onluktaban2.setText("Onluk taban");

        buttonGroup2.add(onaltiliktaban2);
        onaltiliktaban2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        onaltiliktaban2.setText("Onaltılık taban");

        jTextField2.setText("Sonuç..");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ikiliktaban2)
                        .addGap(18, 18, 18)
                        .addComponent(sekizliktaban2)
                        .addGap(18, 18, 18)
                        .addComponent(onluktaban2)
                        .addGap(18, 18, 18)
                        .addComponent(onaltiliktaban2))
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikiliktaban2)
                    .addComponent(sekizliktaban2)
                    .addComponent(onluktaban2)
                    .addComponent(onaltiliktaban2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        cevirButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cevirButton.setText("Çevir");
        cevirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(cevirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cevirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
       
    private static boolean sayiKontrol(String girSayi,int taban) //girilen sayının tabandan büyük olmaması kontrolü
    {  
        char basamak;
        for(int d=0;d<girSayi.length();d++)
        {
            basamak=girSayi.toUpperCase().charAt(d);
            if(Character.isDigit(basamak)&& (basamak-'0')>=taban)
            {
                return false;
            }
            else if(Character.isLetter(basamak)&& !Character.isLetter(basamak))
              {
                JOptionPane.showMessageDialog(null,"Geçersiz basamak" +basamak);
                        
              }
        }
        return true;
    }
    public String onCevirOnalti(int onluk){//onluk tabanı onaltıya dönüştürme
      char[] onaltilik = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                        'A', 'B', 'C', 'D', 'E', 'F'};
       String onalti = "";
       while (onluk != 0) {
          int kalan = onluk % 16;
           onalti = onaltilik[kalan] + onalti;
           onluk = onluk / 16;
          }
            return onalti;
        }
    
    public static int onaltiCevirOn(String onalti){  //onaltılık tabanı onluk tabana dönüştürme
	String onaltilik = "0123456789ABCDEF";  
	onalti= onalti.toUpperCase();  
	int num = 0;  
	for (int i = 0; i < onalti.length(); i++)  
	{  
		char ch = onalti.charAt(i);  
		int n = onaltilik.indexOf(ch);  
		num = 16*num + n;  
	}  
	return num;  
    }
    
    public static String donusum (int onlukSayi, int taban) //onluk tabanlı sayının 2,8 tabana dönüşümü
        {
          String sonucstr="", sonucstr2="";
          while (onlukSayi >= taban)
            {
              int kalan = onlukSayi % taban;
              onlukSayi = onlukSayi / taban;
              sonucstr +=Integer.toString(kalan);
             } 
            sonucstr += Integer.toString(onlukSayi);
            for (int i = sonucstr.length() - 1; i >= 0; i--)
             sonucstr2 += sonucstr.charAt(i);
                         
            return sonucstr2 ;
        }
    
    private void cevirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevirButtonActionPerformed
        // TODO add your handling code here:
        String girilenSayi=jTextField1.getText();
        int onlukSayi=0;
        int sayi;
        char sayiKarakter;
        int ikilikTaban=2,sekizlikTaban=8,onlukTaban=10;
        if(ikiliktaban1.isSelected())//ikilik tabanında girlen sayıyı istenilen tabana dönüştürme
        {
             
          if(girilenSayi.equals("")){
              JOptionPane.showMessageDialog(null,"Lütfen sayı giriniz.."); 
          }
          
          else{
            
              if(sayiKontrol(girilenSayi,2)==true)
              {
                    if(ikiliktaban2.isSelected()) //2 --> 2
                    {
                        jTextField2.setText(girilenSayi);
                    }
                    else if(sekizliktaban2.isSelected()) //2 --> 8
                    {
                      int taban=8;
                      for(int i=0;i<girilenSayi.length();i++)
                       {
                         sayiKarakter=girilenSayi.charAt(i);
                         sayi=Character.digit(sayiKarakter, 10);
                         onlukSayi +=sayi*Math.pow(ikilikTaban,girilenSayi.length()-i-1);
                        }                  
                      jTextField2.setText(donusum(onlukSayi,taban));
                    }
                    else if (onluktaban2.isSelected()) //2 -->10
                    {
                        int taban=10;
                        for(int i=0;i<girilenSayi.length();i++)
                         {
                           sayiKarakter=girilenSayi.charAt(i);
                           sayi=Character.digit(sayiKarakter, taban);
                           onlukSayi +=sayi*Math.pow(ikilikTaban,girilenSayi.length()-i-1);
                           jTextField2.setText(Integer.toString(onlukSayi));
                         }
                    }
                    else if(onaltiliktaban2.isSelected()) //2-->16
                    {
                        for(int i=0;i<girilenSayi.length();i++)
                         {
                           sayiKarakter=girilenSayi.charAt(i);
                           sayi=Character.digit(sayiKarakter, 10);
                           onlukSayi +=sayi*Math.pow(ikilikTaban,girilenSayi.length()-i-1);
                         }
                        String onaltilik = onCevirOnalti(onlukSayi);
                        jTextField2.setText(onaltilik);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Lütfen sonuç tabanı seçiniz..");

                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Lütfen tabana uygun sayı giriniz"); 
                }
             
          }
          
          
        
        }
       
        else if (sekizliktaban1.isSelected()) // sekizlik tabanında girilen sayıyı istenilen tabana dönüştürme
        {
            if(girilenSayi.equals("")){
              JOptionPane.showMessageDialog(null,"Lütfen sayı giriniz.."); 
            }
            else {
            if(sayiKontrol(girilenSayi,8)==true)
              {
                if(sekizliktaban2.isSelected()) //// 8--> 8
                {
                    jTextField2.setText(girilenSayi);
                }
                else if(ikiliktaban2.isSelected()) //8 -->2
                {
                    int taban=2;
                    for(int i=0;i<girilenSayi.length();i++)
                     {
                       sayiKarakter=girilenSayi.charAt(i);
                       sayi=Character.digit(sayiKarakter, 10);
                       onlukSayi +=sayi*Math.pow(sekizlikTaban,girilenSayi.length()-i-1);
                     }
                    jTextField2.setText(donusum(onlukSayi,taban));
                }
                else if(onluktaban2.isSelected()) // 8 -->10
                {
                 for(int i=0;i<girilenSayi.length();i++)
                   {
                      sayiKarakter=girilenSayi.charAt(i);
                      sayi=Character.digit(sayiKarakter, 10);
                      onlukSayi +=sayi*Math.pow(sekizlikTaban,girilenSayi.length()-i-1);
                      jTextField2.setText(Integer.toString(onlukSayi));
                   }
                }
                else if(onaltiliktaban2.isSelected()) // 8 -->16
                {
                 for(int i=0;i<girilenSayi.length();i++)
                  {
                    sayiKarakter=girilenSayi.charAt(i);
                    sayi=Character.digit(sayiKarakter, 10);
                    onlukSayi +=sayi*Math.pow(sekizlikTaban,girilenSayi.length()-i-1);
                  }
                    String onaltilik = onCevirOnalti(onlukSayi);
                    jTextField2.setText(onaltilik);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Lütfen sonuç tabanı seçiniz..");
                }
              }
              else
                {
                    JOptionPane.showMessageDialog(null,"Lütfen tabana uygun sayı giriniz"); 
                }
          }
        }
        else if(onluktaban1.isSelected()) //onluk tabanlı sayının dönüşümü
        {
            if(girilenSayi.equals("")){
              JOptionPane.showMessageDialog(null,"Lütfen sayı giriniz.."); 
            }
            else {
            
            if(onluktaban2.isSelected())//10-->10
            {
                jTextField2.setText(girilenSayi);
            }
            else if(ikiliktaban2.isSelected()) //10 -->2
            {
                for(int i=0;i<girilenSayi.length();i++)
                 {
                  sayiKarakter=girilenSayi.charAt(i);
                  sayi=Character.digit(sayiKarakter, 10);
                  onlukSayi +=sayi*Math.pow(onlukTaban,girilenSayi.length()-i-1);
                 }
                int taban=2;
                jTextField2.setText(donusum(onlukSayi,taban));
            }
            else if(sekizliktaban2.isSelected()) //10-->8
            {
                for(int i=0;i<girilenSayi.length();i++)
                 {
                  sayiKarakter=girilenSayi.charAt(i);
                  sayi=Character.digit(sayiKarakter, 10);
                  onlukSayi +=sayi*Math.pow(onlukTaban,girilenSayi.length()-i-1);
                 }
                int taban=8;
                jTextField2.setText(donusum(onlukSayi,taban));
            }
            else if(onaltiliktaban2.isSelected()) //10-->16
            {
                int onluk = Integer.parseInt(girilenSayi);
                String onaltilik = onCevirOnalti(onluk);
                jTextField2.setText(onaltilik);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Lütfen sonuç tabanı seçiniz..");
            }
            }
        }
        else if(onaltiliktaban1.isSelected()) //onaltılık tabanlı sayının dönüşümü
        {
            if(girilenSayi.equals("")){
              JOptionPane.showMessageDialog(null,"Lütfen sayı giriniz.."); 
            }
            else {
            if(onaltiliktaban2.isSelected())//16-->16
            {
                jTextField2.setText(girilenSayi);
            }
            else if(ikiliktaban2.isSelected()) //16 -->2
            {
                int taban=2;
                int onluk =onaltiCevirOn(girilenSayi);
                jTextField2.setText(donusum(onluk,taban));
            }
            else if(sekizliktaban2.isSelected()) //16 -->8
            {
                int taban=8;
                int onluk =onaltiCevirOn(girilenSayi);
                jTextField2.setText(donusum(onluk,taban));
            }
            else if(onluktaban2.isSelected()) //16 -->10
            {
              int onluk =onaltiCevirOn(girilenSayi);
              jTextField2.setText(Integer.toString(onluk));
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Lütfen sonuç tabanı seçiniz..");
            }
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Lütfen çevrilecek tabanı seçiniz..");
        }
    }//GEN-LAST:event_cevirButtonActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
       if(!(onaltiliktaban1.isSelected()))
        { char vchar = evt.getKeyChar();
             if(!(Character.isDigit(vchar)||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE)))
             {
                 evt.consume();
             }
        }
        
        
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sayiTabanUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sayiTabanUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sayiTabanUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sayiTabanUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sayiTabanUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cevirButton;
    private javax.swing.JRadioButton ikiliktaban1;
    private javax.swing.JRadioButton ikiliktaban2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton onaltiliktaban1;
    private javax.swing.JRadioButton onaltiliktaban2;
    private javax.swing.JRadioButton onluktaban1;
    private javax.swing.JRadioButton onluktaban2;
    private javax.swing.JRadioButton sekizliktaban1;
    private javax.swing.JRadioButton sekizliktaban2;
    // End of variables declaration//GEN-END:variables
}
